import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce-site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
    {/* px-40 py-6 bg-slate-50 */}
      <body className={`${inter.className} bg-slate-50`}>
      <Navbar/>
       <div>
        {children}
       </div>
        <Footer />
        </body>
    </html>
  );
}
